
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('listings').del()
    .then(function () {
      // Inserts seed entries
      return knex('listings').insert([
        { id: 1, member_id: 1, category_id: 1,title: 'Table tennis paddle', description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', image_URL: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Shakehand1.jpg', cost_in_cents: 0 },
        { id: 2, member_id: 2, category_id: 2, title: 'Rocking Chair', description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', image_URL: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Ackerman_farmer.jpg', cost_in_cents: 0 },
        { id: 3, member_id: 3, category_id: 3, title: 'My Dog', description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', image_URL: 'https://upload.wikimedia.org/wikipedia/commons/6/64/Boxer_on_a_couch.JPG', cost_in_cents: 0 },
        { id: 4, member_id: 4, category_id: 4, title: 'Boyfriend to loan', description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', image_URL: 'https://upload.wikimedia.org/wikipedia/commons/7/7f/EliasBenjamin.jpg', cost_in_cents: 0 },
        { id: 5, member_id: 5, category_id: 5,title: 'Motorhome', description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', image_URL: 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Breezer_A.jpg', cost_in_cents: 0 },
        { id: 6, member_id: 6, category_id: 6, title: 'Dinning suite', description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', image_URL: 'https://upload.wikimedia.org/wikipedia/commons/1/17/Dining_table_for_two.jpg', cost_in_cents: 0 },
        { id: 7, member_id: 7, category_id: 7, title: 'Necklace', description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', image_URL: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Onyx_Pearls_Necklace-1200.jpg', cost_in_cents: 0 },
        { id: 8, member_id: 8, category_id: 8, title: 'Shoes', description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', image_URL: 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Red_shoes.jpg', cost_in_cents: 0 },
        { id: 9, member_id: 9, category_id: 9, title: 'Blue dress', description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', image_URL: 'https://upload.wikimedia.org/wikipedia/commons/2/25/Abstract_Floral_Blue_80s_Dress_with_Bright_Red_Hair_%2819591253151%29.jpg', cost_in_cents: 0 },
        { id: 10, member_id: 10, category_id: 10, title: 'Cow', description: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).', image_URL: 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Drev_chez_Yannig_Coulomb_%26_Ga%C3%ABlle_Kerl%C3%A9guer.jpg', cost_in_cents: 0 }
      ]);
    });
  // exports.seed = function (knex, Promise) {
  //     // Deletes ALL existing entries
  //     return knex('listings').del()
  //         .then(function () {
  //             // Inserts seed entries
  //             return knex('listings').insert([
  //                 { id: 1, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist1', member_id: 1, category_id: 1, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
  //                 { id: 2, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist2', member_id: 2, category_id: 2, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
  //                 { id: 3, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist3', member_id: 3, category_id: 3, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 }
  //                 ,
  //                 { id: 4, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist4', member_id: 4, category_id: 4, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
  //                 { id: 5, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist5', member_id: 5, category_id: 5, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
  //                 { id: 6, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist6', member_id: 6, category_id: 6, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
  //                 { id: 7, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist7', member_id: 7, category_id: 7, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
  //                 { id: 8, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist8', member_id: 8, category_id: 8, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
  //                 { id: 9, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist9', member_id: 9, category_id: 9, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
  //                 { id: 10, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist10', member_id: 10, category_id: 10, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 }
  //             ]);
  //         });
};
