
exports.seed = function (knex, Promise) {
    // Deletes ALL existing entries
    return knex('listings').del()
        .then(function () {
            // Inserts seed entries
            return knex('listings').insert([
                { id: 1, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist1', member_id: 1, category_id: 1, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
                { id: 2, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist2', member_id: 2, category_id: 2, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
                { id: 3, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist3', member_id: 3, category_id: 3, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 }
                ,
                { id: 4, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist4', member_id: 4, category_id: 4, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
                { id: 5, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist5', member_id: 5, category_id: 5, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
                { id: 6, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist6', member_id: 6, category_id: 6, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
                { id: 7, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist7', member_id: 7, category_id: 7, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
                { id: 8, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist8', member_id: 8, category_id: 8, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
                { id: 9, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist9', member_id: 9, category_id: 9, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 },
                { id: 10, image_URL: 'https://cintesi-co-nz.imgix.net/products/wire-coffee-table-black-98wirebk-main.jpg?w=800&h=1000&fit=fillmax&auto=format&trimcolor=FFFFFF&trim=color&bg=fff&s=1f7661a07c300ed8054b0be8f199a6f6', title: 'mylist10', member_id: 10, category_id: 10, description: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.', cost_in_cents: 0 }
            ]);
        });
};
