
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('members').del()
    .then(function () {
      // Inserts seed entries
      return knex('members').insert([
        { id: 1, username: "scrubscrub1", name: "Eddie Haynes", about_me: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", town: "Timaru", email: "blah@blah.blah", image_URL: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/peter-dinklage-look-1536330273.jpg" },
        { id: 2, username: "noscrub1", name: "Loretta Nickerson", about_me: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", town: "Napier", email: "blah@blah.blah", image_URL: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/peter-dinklage-look-1536330273.jpg" },
        { id: 3, username: "toscrub1", name: "Lue Hamrick", about_me: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", town: "Auckland", email: "blah@blah.blah", image_URL: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/peter-dinklage-look-1536330273.jpg" },
        { id: 4, username: "prettyscrub1", name: "Barbara Helm", about_me: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", town: "Christchurch", email: "blah@blah.blah", image_URL: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/peter-dinklage-look-1536330273.jpg" },
        { id: 5, username: "totalscrub1", name: "Grover Taylor", about_me: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", town: "Paraparaumu", email: "blah@blah.blah", image_URL: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/peter-dinklage-look-1536330273.jpg" },
        { id: 6, username: "whyscrub1", name: "Mildred Cohen", about_me: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", town: "Thames", email: "blah@blah.blah", image_URL: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/peter-dinklage-look-1536330273.jpg" },
        { id: 7, username: "bubbascrub1", name: "Nadine Neal", about_me: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", town: "Whakatane", email: "blah@blah.blah", image_URL: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/peter-dinklage-look-1536330273.jpg" },
        { id: 8, username: "scrub1", name: "Gary Kavanaugh", about_me: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", town: "Lincoln", email: "blah@blah.blah", image_URL: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/peter-dinklage-look-1536330273.jpg" },
        { id: 9, username: "tomuchscrub1", name: "Charline Elsass", about_me: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", town: "Tauranga", email: "blah@blah.blah", image_URL: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/peter-dinklage-look-1536330273.jpg" },
        { id: 10, username: "severalscrub1", name: "Helen Burrows", about_me: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", town: "Hamilton", email: "blah@blah.blah", image_URL: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/peter-dinklage-look-1536330273.jpg" }
      ]);
    });
};
